version: '3.7'

secrets:
  ca_chain:
    file: configs/ca/chain.crt
  mongo_crt_key:
    file: configs/mongodb/mongodb.crt_key
  rabbitmq_key:
    file: configs/rabbitmq/rabbitmq.key
  rabbitmq_crt:
    file: configs/rabbitmq/rabbitmq.crt

volumes:
  mongo:
    name: "mongo"

services:
  mongodb:
    image: mongo
    deploy:
      restart_policy:
        delay: 1s
        condition: any
    deploy:
      replicas: 1
    ports:
      - 27017:27017
    secrets:
      - source: mongo_crt_key
        mode: 420
    env_file: configs/mongodb/var.env
    volumes:
      - type: volume
        source: mongo
        target: /data/db
    command:
      - mongod
      - "--bind_ip_all"
      - "--tlsMode"
      - requireTLS
      - "--tlsCertificateKeyFile"
      - /run/secrets/mongo_crt_key

  rabbitmq:
    image: rabbitmq:3-management
    deploy:
      restart_policy:
        delay: 1s
        condition: any
      mode: replicated
      replicas: 1
    secrets:
      - source: rabbitmq_key
        mode: 420
      - source: rabbitmq_crt
        mode: 420
      - source: ca_chain
        mode: 420
    ports:
      - 15671:15671
      - 5671:5671
    env_file: configs/rabbitmq/var.env
    environment:
      RABBITMQ_USE_LONGNAME: 1
      RABBITMQ_MANAGEMENT_SSL_CACERTFILE: /run/secrets/ca_chain
      RABBITMQ_MANAGEMENT_SSL_CERTFILE: /run/secrets/rabbitmq_crt
      RABBITMQ_MANAGEMENT_SSL_DEPTH: 1
      RABBITMQ_MANAGEMENT_SSL_FAIL_IF_NO_PEER_CERT: 0 
      RABBITMQ_MANAGEMENT_SSL_KEYFILE: /run/secrets/rabbitmq_key
      RABBITMQ_MANAGEMENT_SSL_VERIFY: verify_peer
      RABBITMQ_SSL_CACERTFILE: /run/secrets/ca_chain
      RABBITMQ_SSL_CERTFILE: /run/secrets/rabbitmq_crt
      RABBITMQ_SSL_DEPTH: 1
      RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT: 0
      RABBITMQ_SSL_KEYFILE: /run/secrets/rabbitmq_key
      RABBITMQ_SSL_VERIFY: verify_peer

  daily_refresh_job:
    image: gcr.io/production-280612/data/daily_refresh_job:v0.0.4
    deploy:
      restart_policy:
        delay: 1s
        condition: any
    deploy:
      replicas: 1
    secrets:
      - source: ca_chain
        mode: 420
    env_file: configs/daily_refresh_job/var.env
    environment:
      DEBUG: "false"
      ENVIRONMENT: PROD

      CA_CHAIN: /run/secrets/ca_chain

      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DATABASE: bezunca

      QUEUE_HOST: rabbitmq
      QUEUE_PORT: 5671
      QUEUE_SELF_SIGNED: 1

      INITIAL_B3_YEAR: 2015

      CRON_ENABLE: "true"
      CRON_SCHEDULE_PATTERN: "0 1 * * *"

  bezuncapi:
    image: gcr.io/production-280612/data/bezuncapi:v0.0.6
    deploy:
      restart_policy:
        delay: 1s
        condition: any
    deploy:
      replicas: 1
    ports:
      - 80:8080
    secrets:
      - source: ca_chain
        mode: 420
    env_file: configs/bezuncapi/var.env
    environment:
      DEBUG: "true"
      ADDRESS: 0.0.0.0
      PORT: 8080

      CA_CHAIN: /run/secrets/ca_chain

      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_USER: root

      WEB_URL: "https://bezunca.com.br/"
      DYNAMIC_LINK: "https://bezunca.page.link/"
      FLUTTER_ANDROID_APP_ID: "com.bezunca.app"
